FROM ghcr.io/pikaos-linux/pikaos-base:canaryv3
RUN apt-get update -y && apt-get -y install software-properties-common sudo git bc gpg gpg-agent bison build-essential cargo rustc pahole libelf-dev nodejs npm ccache cmake cpio fakeroot flex git kmod libelf-dev libncurses5-dev libssl-dev lz4 qtbase5-dev rsync schedtool wget zstd tar devscripts dh-make rpm2cpio mesa-stable-no-march -y
