FROM ghcr.io/pikaos-linux/pikaos-base:canaryi386
RUN apt-get update -y
RUN apt-get -y install sudo git bc gpg gpg-agent bison build-essential nodejs npm ccache cmake cpio fakeroot flex git kmod libelf-dev libncurses5-dev libssl-dev lz4 qtbase5-dev rsync wget zstd tar devscripts dh-make ssh -y
