name: Build pikaos-base Nest Image and push to registry (amd64-v3)

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cruizba/ubuntu-dind:systemd-latest
      volumes:
        - /proc:/proc
      options: --privileged -it
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./base-nestv3/
          push: true
          tags: ghcr.io/pikaos-linux/pikaos-base:nestv3

          
