name: Build pikaos-base Nest Image and push to registry (amd64-v3)

on:
  workflow_dispatch:

env:
  IMAGE_NAME: pikaos-base
  IMAGE_VERSION: nestv3

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .base-nestv3/
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$IMAGE_VERSION

          
